name: Auto Sync Fork

on:
  schedule:
    # 每天 UTC 时间凌晨 2 点（北京时间上午 10 点）自动执行
    - cron: '0 2 * * *'
  workflow_dispatch: # 允许你随时手动点击运行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Sync Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: ccfddl/ccf-deadlines
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false
